quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/gestao
quarkus.datasource.username=${QUARKUS_DATASOURCE_USERNAME}
quarkus.datasource.password=${QUARKUS_DATASOURCE_PASSWORD}

# Hibernate: criar schema automaticamente
quarkus.hibernate-orm.database.generation=create-drop
quarkus.hibernate-orm.database.generation.create-schemas=true
quarkus.hibernate-orm.sql-load-script=initdb/init.sql

quarkus.http.port=8090

#configuracoes de log
quarkus.log.level=INFO
quarkus.log.category."com.empresa".level=DEBUG

#test
quarkus.http.test-port=0

# OpenAPI/Swagger
quarkus.smallrye-openapi.path=/q/openapi
quarkus.swagger-ui.path=/doc
quarkus.swagger-ui.always-include=true
quarkus.smallrye-openapi.info-title=Gestao de Solicitacoes API
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.smallrye-openapi.info-description=API para gerenciamento de solicitacoes
quarkus.smallrye-openapi.servers=http://localhost:8090